name: sentiment-analysis
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pytorch
  - pip:
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - transformers>=4.11.3
    - pydantic>=1.8.2
    - pytest>=6.2.5
    - httpx>=0.19.0